linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused 
    - varcheck
    - goimports
    - cyclop
    - errname
    - errorlint
    - misspell